spring:
  kafka:
      bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://abid:abid72raza@ds125945.mlab.com:25945/bookstoredb?retryWrites=false
      database: bookstoredb
app:
  topic:
    example: test
